### ISSUE TITLE
SPI Issue for multiple device

### ISSUE THREAD

**Issue by ecaits** [PaulStoffregen/SPI#25]
Hello,
I am interfacing TFT and SD card with arduino mega board and running a simple code, given below, but sd card is not initialized. \

#include "SPI.h"
#include "Adafruit_GFX.h"
#include "Adafruit_ILI9341.h"

#include <Wire.h>
#include <SD.h>

#define TFT_RST 8
#define TFT_DC 9
#define TFT_CS A5

File myFile;

Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC, TFT_RST);

#define HALF_CLOCK_PERIOD 1 

void setup()
{
  Serial.begin(9600); 
  SPI.begin();
  pinMode(53, OUTPUT);

  if (!SD.begin(53)) {
  Serial.println("SD initialization failed!");
  }
  else Serial.println("SD Card initialization done.");
 
  tft.begin(); 
  tft.println("Welcome");
}

void loop()
{

}

When I remove the MISO pin of TFT, at that time SD card is initialized and working normal.
I think it is a SPI based issue. I have tried a lot but could not get the success.
How can i solve the issue?

How can I generate a separate MISO & MOSI pin for SD card and other slaves??

**Comment by PaulStoffregen** [comment]
This is the wrong place to ask.

1: Github issues are not the place for *any* project help.

2: This one is for Teensy, not Arduino Mega.

Ask for help here:

http://forum.arduino.cc/
