### ISSUE TITLE
 error: 'SPIClass' does not name a type  extern SPIClass SPI;

### ISSUE THREAD

**Issue by 4711engel** [PaulStoffregen/SPI#49]
Hallo Paul,
ich habe folgendes Problem beim Kompilieren eines sketches.
Fehlermeldung:

In file included from InternetClock_ILI9341.ino:18:0:
C:\Users\uengel\Documents\Arduino\libraries\SPI/SPI.h:1378:8: error: 'SPIClass' does not name a type
 extern SPIClass SPI;
        ^
In file included from InternetClock_ILI9341.ino:19:0:
C:\Users\uengel\Documents\Arduino\libraries\TFT_ILI9341_ESP/TFT_ILI9341_ESP.h:496:13: error: 'SPIClass' does not name a type
             SPIClass *_SPI;
             ^

Ich verwende IDE 1.6.5 und den sketch aus dem Tutorial:
http://embedded-lab.com/blog/tutorial-8-esp8266-internet-clock/?unapproved=2458495&moderation-hash=81156ba4e4b884bbeaff565d3e6be302#comment-2458495

Da ich Anfänger bin, habe ich bis jetzt keine Erklärung für den SPI-Fehler.
Kannst Du helfen?

Danke
Ulli

[TFT_ILI9341_ESP-master.zip](https://github.com/PaulStoffregen/SPI/files/3388746/TFT_ILI9341_ESP-master.zip)
[InternetClock_ILI9341.zip](https://github.com/PaulStoffregen/SPI/files/3388751/InternetClock_ILI9341.zip)

**Comment by PaulStoffregen** [comment]
You're posted in the wrong place.  This is the SPI library for Teensy.  It is not for ESP chips.
