### ISSUE TITLE
SPI-half duplex support

### ISSUE THREAD

**Issue by warriorfenixSM** [PaulStoffregen/SPI#52]
Hi!

I need your help to know if the library support 3-wire SPI and if yes. How?

I attacht the picture.

I need to control a Optical track Sensor.

![image](https://user-images.githubusercontent.com/30696031/64736184-5da45f80-d4ea-11e9-8b5d-1a6a8bf95a27.png)

Please i need your help!.

Thanks

[PAT9130EW - AN04 SPI ControlFlow V0.1.pdf](https://github.com/PaulStoffregen/SPI/files/3602779/PAT9130EW.-.AN04.SPI.ControlFlow.V0.1.pdf)
[PAT9130EW-TKMT_GDS-R1.0_12062017_21006AEN.pdf](https://github.com/PaulStoffregen/SPI/files/3602780/PAT9130EW-TKMT_GDS-R1.0_12062017_21006AEN.pdf)

**Comment by PaulStoffregen** [comment]
This is not the place for questions.  Ask on the forum.  The issue tracker is only for reporting software defects.
