### ISSUE TITLE
Problem with SPI.begin transaction

### ISSUE THREAD

**Issue by warriorfenixSM** [PaulStoffregen/SPI#53]
Hi the instruction spi.begintransaction not works

![image](https://user-images.githubusercontent.com/30696031/64896027-af7dee80-d67e-11e9-98ed-ed2520e30da3.png)

**Comment by PaulStoffregen** [comment]
This is not the place for questions. Ask on the forum. The issue tracker is only for reporting software defects.

This was explained on #52.  Please, do not open more issues to ask question.  It only wastes time.
