### ISSUE TITLE
Use of deprecated functions.

### ISSUE THREAD

**Issue by sophiekovalevsky** [PaulStoffregen/SPI#9]
Hi there. thanks for this amazing tool.
I've read recently about the new use of beginTransaction to work properly with several slave devices. 
I'm wondering what should be the best approach to remove old methods such: bitOrder and setMode to work properly with beginTransaction when the code only works with only one slave.

I've read that there is no need to use settings if only one slave is used, but not use how to proceed is I need to remove deprecated methods. 

Thanks in advances

**Comment by PaulStoffregen** [comment]
Use of beginTransaction, it overrides bitOrder and setMode.

**Comment by sophiekovalevsky** [comment]
Thanks.
